back-end/config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :cows
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

back-end/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

back-end/app/models/cow.rb
class Cow < ApplicationRecord
  belongs_to :user
  
   #These validation rules are in place to ensure correct data is gathered
   validates :tag, presence: true, length: { minimum: 5, maximum: 5 }, uniqueness: true
   validates :dob, presence: true
   validates :breed, presence: true
   validates :dam, presence: true, length: { minimum: 5, maximum: 5 }
   validates :docility, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
   validates :aggression, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
   validates :fertility, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
   validates :calving, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
   validates :milk, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
   validates :calfquality, presence: true,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
 
end

back-end/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :cow
end

back-end/app/models/user.rb
class User < ApplicationRecord
end

back-end/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

back-end/app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :set_cow, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception, unless: -> {request.format.json?}


  # GET /cows or /cows.json
  def index
    @cows = Cow.all
  end

  # GET /cows/1 or /cows/1.json
  def show
  end

  # GET /cows/new
  def new
    @cow = Cow.new
  end

  # GET /cows/1/edit
  def edit
  end

  # POST /cows or /cows.json
  def create
    @cow = Cow.new(cow_params)

    respond_to do |format|
      if @cow.save
        format.html { redirect_to cow_url(@cow), notice: "Cow was successfully created." }
        format.json { render :show, status: :created, location: @cow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cows/1 or /cows/1.json
  def update
    respond_to do |format|
      if @cow.update(cow_params)
        format.html { redirect_to cow_url(@cow), notice: "Cow was successfully updated." }
        format.json { render :show, status: :ok, location: @cow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cows/1 or /cows/1.json
  def destroy
    @cow.destroy

    respond_to do |format|
      format.html { redirect_to cows_url, notice: "Cow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cow
      @cow = Cow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cow_params
      params.require(:cow).permit(:tag, :dob, :dam, :breed, :docility, :aggression, :fertility, :calving, :calfquality, :milk, :user_id)
    end
end

back-end/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception, unless: -> {request.format.json?}
  
  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :cow_id)
    end
end

back-end/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception, unless: -> {request.format.json?}


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email)
    end
end

back-end/app/helpers/application_helper.rb
module ApplicationHelper
end

back-end/app/helpers/cows_helper.rb
module CowsHelper
end

back-end/app/helpers/notes_helper.rb
module NotesHelper
end

back-end/app/helpers/users_helper.rb
module UsersHelper
end

back-end/app/views/cows/_cow.html.erb
<div id="<%= dom_id cow %>">
  <p>
    <strong>Tag:</strong>
    <%= cow.tag %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= cow.dob %>
  </p>

  <p>
    <strong>Dam:</strong>
    <%= cow.dam %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= cow.breed %>
  </p>

  <p>
    <strong>Docility:</strong>
    <%= cow.docility %>
  </p>

  <p>
    <strong>Aggression:</strong>
    <%= cow.aggression %>
  </p>

  <p>
    <strong>Fertility:</strong>
    <%= cow.fertility %>
  </p>

  <p>
    <strong>Calving:</strong>
    <%= cow.calving %>
  </p>

  <p>
    <strong>Calfquality:</strong>
    <%= cow.calfquality %>
  </p>

  <p>
    <strong>Milk:</strong>
    <%= cow.milk %>
  </p>

  <p>
    <strong>User:</strong>
    <%= cow.user_id %>
  </p>

</div>

back-end/app/views/cows/_form.html.erb
<%= form_with(model: cow) do |form| %>
  <% if cow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cow.errors.count, "error") %> prohibited this cow from being saved:</h2>

      <ul>
        <% cow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tag, style: "display: block" %>
    <%= form.number_field :tag %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :dam, style: "display: block" %>
    <%= form.number_field :dam %>
  </div>

  <div>
    <%= form.label :breed, style: "display: block" %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :docility, style: "display: block" %>
    <%= form.number_field :docility %>
  </div>

  <div>
    <%= form.label :aggression, style: "display: block" %>
    <%= form.number_field :aggression %>
  </div>

  <div>
    <%= form.label :fertility, style: "display: block" %>
    <%= form.number_field :fertility %>
  </div>

  <div>
    <%= form.label :calving, style: "display: block" %>
    <%= form.number_field :calving %>
  </div>

  <div>
    <%= form.label :calfquality, style: "display: block" %>
    <%= form.number_field :calfquality %>
  </div>

  <div>
    <%= form.label :milk, style: "display: block" %>
    <%= form.number_field :milk %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/cows/edit.html.erb
<h1>Editing cow</h1>

<%= render "form", cow: @cow %>

<br>

<div>
  <%= link_to "Show this cow", @cow %> |
  <%= link_to "Back to cows", cows_path %>
</div>

back-end/app/views/cows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cows</h1>

<div id="cows">
  <% @cows.each do |cow| %>
    <%= render cow %>
    <p>
      <%= link_to "Show this cow", cow %>
    </p>
  <% end %>
</div>

<%= link_to "New cow", new_cow_path %>

back-end/app/views/cows/new.html.erb
<h1>New cow</h1>

<%= render "form", cow: @cow %>

<br>

<div>
  <%= link_to "Back to cows", cows_path %>
</div>

back-end/app/views/cows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cow %>

<div>
  <%= link_to "Edit this cow", edit_cow_path(@cow) %> |
  <%= link_to "Back to cows", cows_path %>

  <%= button_to "Destroy this cow", @cow, method: :delete %>
</div>

back-end/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackEnd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back-end/app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :cow_id, style: "display: block" %>
    <%= form.text_field :cow_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= note.body %>
  </p>

  <p>
    <strong>Cow:</strong>
    <%= note.cow_id %>
  </p>

</div>

back-end/app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

back-end/app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

back-end/app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

back-end/app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>

back-end/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

back-end/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

back-end/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

back-end/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

back-end/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>